language: swift
osx_image: xcode10.2
sudo: false

env:
  global:
    - WORKSPACE=Xcode/JetPack.xcworkspace
    - IOS_DEVICE_SDK=iphoneos12.2
    - IOS_SIMULATOR_SDK=iphonesimulator12.2
  matrix:
    - POD_LINT="yes"
    - SDK="$IOS_SIMULATOR_SDK" SCHEME="All"                           CONFIGURATION="Debug"   DESTINATION="OS=12.2,name=iPhone 8"
    - SDK="$IOS_SIMULATOR_SDK" SCHEME="All"                           CONFIGURATION="Release" DESTINATION="OS=12.2,name=iPhone 8" SWIFT_OPTIMIZATION_LEVEL="-Owholemodule"
    - SDK="$IOS_SIMULATOR_SDK" SCHEME="Extensions-CoreGraphics-Tests" CONFIGURATION="Debug"   DESTINATION="OS=11.4,name=iPhone 8"
    - SDK="$IOS_SIMULATOR_SDK" SCHEME="Extensions-CoreGraphics-Tests" CONFIGURATION="Release" DESTINATION="OS=11.4,name=iPhone 8" SWIFT_OPTIMIZATION_LEVEL="-Owholemodule"
    - SDK="$IOS_SIMULATOR_SDK" SCHEME="Extensions-Foundation-Tests"   CONFIGURATION="Debug"   DESTINATION="OS=11.4,name=iPhone 8"
    - SDK="$IOS_SIMULATOR_SDK" SCHEME="Extensions-Foundation-Tests"   CONFIGURATION="Release" DESTINATION="OS=11.4,name=iPhone 8" SWIFT_OPTIMIZATION_LEVEL="-Owholemodule"
    - SDK="$IOS_SIMULATOR_SDK" SCHEME="Extensions-Swift-Tests"        CONFIGURATION="Debug"   DESTINATION="OS=11.4,name=iPhone 8"
    - SDK="$IOS_SIMULATOR_SDK" SCHEME="Extensions-Swift-Tests"        CONFIGURATION="Release" DESTINATION="OS=11.4,name=iPhone 8" SWIFT_OPTIMIZATION_LEVEL="-Owholemodule"
    - SDK="$IOS_SIMULATOR_SDK" SCHEME="UI-Tests"                      CONFIGURATION="Debug"   DESTINATION="OS=11.4,name=iPhone 8"
    - SDK="$IOS_SIMULATOR_SDK" SCHEME="UI-Tests"                      CONFIGURATION="Release" DESTINATION="OS=11.4,name=iPhone 8" SWIFT_OPTIMIZATION_LEVEL="-Owholemodule"
    
before_install:
  - gem install cocoapods xcpretty xcpretty-travis-formatter --no-document --quiet

script:
  - Xcode/Tests/Travis.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)
