language: objective-c
osx_image: xcode8
sudo: false

env:
  global:
    - WORKSPACE=Xcode/Project.xcworkspace
    - IOS_DEVICE_SDK=iphoneos10.0
    - IOS_SIMULATOR_SDK=iphonesimulator10.0
  matrix:
    - POD_LINT="yes"
    - SDK="$IOS_DEVICE_SDK"    SCHEME="All"                     CONFIGURATION="Debug"
    - SDK="$IOS_DEVICE_SDK"    SCHEME="All"                     CONFIGURATION="Release" SWIFT_OPTIMIZATION_LEVEL="-O"
    - SDK="$IOS_DEVICE_SDK"    SCHEME="All"                     CONFIGURATION="Release" SWIFT_OPTIMIZATION_LEVEL="-Owholemodule"
    - SDK="$IOS_SIMULATOR_SDK" SCHEME="All"                     CONFIGURATION="Debug"   DESTINATION="OS=10.0,name=iPhone 7"
    - SDK="$IOS_SIMULATOR_SDK" SCHEME="All"                     CONFIGURATION="Release" DESTINATION="OS=10.0,name=iPhone 7" SWIFT_OPTIMIZATION_LEVEL="-Owholemodule"
    - SDK="$IOS_SIMULATOR_SDK" SCHEME="Extensions-CoreGraphics" CONFIGURATION="Debug"   DESTINATION="OS=9.3,name=iPhone 4S"
    - SDK="$IOS_SIMULATOR_SDK" SCHEME="Extensions-CoreGraphics" CONFIGURATION="Release" DESTINATION="OS=9.3,name=iPhone 7" SWIFT_OPTIMIZATION_LEVEL="-Owholemodule"
    - SDK="$IOS_SIMULATOR_SDK" SCHEME="Extensions-Foundation"   CONFIGURATION="Debug"   DESTINATION="OS=9.2,name=iPhone 4S"
    - SDK="$IOS_SIMULATOR_SDK" SCHEME="Extensions-Foundation"   CONFIGURATION="Release" DESTINATION="OS=9.2,name=iPhone 7" SWIFT_OPTIMIZATION_LEVEL="-Owholemodule"
    - SDK="$IOS_SIMULATOR_SDK" SCHEME="Extensions-Swift"        CONFIGURATION="Debug"   DESTINATION="OS=9.1,name=iPhone 4S"
    - SDK="$IOS_SIMULATOR_SDK" SCHEME="Extensions-Swift"        CONFIGURATION="Release" DESTINATION="OS=9.1,name=iPhone 7" SWIFT_OPTIMIZATION_LEVEL="-Owholemodule"
    
before_install:
  - gem install cocoapods -v 1.1.0.rc.2 --no-rdoc --no-ri --no-document --quiet
  - gem install xcpretty xcpretty-travis-formatter --no-rdoc --no-ri --no-document --quiet

script:
  - Xcode/Tests/Travis.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  slack:
    rooms:
      secure: O1mImcr+B50sT8mcrY5BbO2WKVfXXIwAGXTH0qgOjR1OEEaJWcg5xrkJbyO55DQEAMsoqaupA5DgFEgShGHZ94HWyr30z6qlCO/CEC9+syRV9vLV/s0CEmnGJDMCSK6gYqwcJsk7S1iawPWRVOPjt8QUZ7O5+c/mrfUitlf2BOY=
    on_success: change
    on_failure: change
    on_start:   never
